export const experience = [
  { date: "SEP 2025 — PRESENT", employer: "Lowe’s", title: "Software Engineer", team: "AI Agents & Enterprise Workflows", summary: "Building full-stack AI applications that connect conversational experiences with real business systems. Work spans customer shopping, analytics, enterprise automation, authorization, and production reliability.", tags: ["Full-stack", "Applied AI", "Enterprise systems"] },
  { date: "JUN 2024 — SEP 2025", employer: "Lowe’s", title: "Associate Software Engineer", team: "Product Detail Page", summary: "Delivered customer-facing experiences, improved analytics accuracy, extended content management capabilities, and built internal developer tools. Partnered with product and engineering teams on experimentation and application security.", tags: ["Web applications", "Experimentation", "Developer tooling"] },
  { date: "MAY — AUG 2023", employer: "Lowe’s", title: "Front-End Web Development Intern", team: "Web & Mobile Experiences", summary: "Integrated push notifications and native-to-web data flows, with automated testing and continuous integration supporting delivery.", tags: ["React", "Firebase", "Capacitor"] },
  { date: "JUN — SEP 2022", employer: "Hawkeye MedTech", title: "Web Development Intern", team: "Health Technology", summary: "Connected smartwatch health data with user profiles and built interactive visualizations, with attention to cross-device compatibility.", tags: ["API integration", "Data visualization"] },
];
export const contributions = [
  { icon: "workflow", category: "FULL-STACK × APPLIED AI", year: "2026", shortTitle: "Enterprise AI workflows", title: "Turning complex operations into guided workflows.", summary: "Built an AI-powered enterprise assistant that connects a modern web interface, backend services, and business systems to simplify multi-step operations.", tags: ["React / TypeScript", "Python / FastAPI", "LangGraph", "PostgreSQL"], role: "Built across frontend, backend, and enterprise integrations", outcome: "Guided enterprise workflows shipped to production", details: [
    { heading: "The problem", body: "Business operations required navigating multiple systems, understanding specialized fields, and completing dependent steps correctly. A conversational interface needed to make that process easier while preserving control over consequential changes." },
    { heading: "My contribution", body: "Owned substantial work across the React interface, Python backend, workflow framework, persistence, and enterprise integrations. Delivered guided item creation and management workflows, product classification recommendations, and structured feedback capture." },
    { heading: "Engineering decisions", body: "Built server-enforced permissions and approval-controlled execution. Designed durable progress tracking and partial-failure recovery so completed work is preserved and uncertain outcomes can be verified before another write. Prediction services degrade gracefully and keep people in control of recommendations." },
    { heading: "The result", body: "Delivered production workflows that bring complex operations into a guided experience, with approval, operational visibility, and recovery built into the application. Established reusable foundations for additional enterprise workflows." },
  ] },
  { icon: "commerce", category: "APPLIED AI × FULL-STACK", year: "2025–2026", shortTitle: "Conversational commerce", title: "Making business transactions conversational.", summary: "Helped build a customer-facing shopping agent that brings product discovery, carts, quotes, orders, and account-aware actions into a natural-language experience.", tags: ["Conversational AI", "API integration", "Authentication", "Evaluation"], role: "Co-architected the experience and delivered account workflows", outcome: "Shopping and account actions live in production", details: [
    { heading: "The problem", body: "Shopping and account workflows often require several screens and manual handoffs. A conversational alternative needed to support useful actions while respecting account boundaries and business rules." },
    { heading: "My contribution", body: "Co-architected the customer-facing experience and delivered authentication, account-restricted behavior, session-aware workflows, and deployment integration. Improved quote editing, order-number recognition, purchase-order updates, and image-based quote fallback behavior." },
    { heading: "Engineering decisions", body: "Separated shopping and analytics responsibilities, added explicit confirmations for ambiguous actions, and evaluated orchestration performance across shopping, insights, and mixed workflows. Used benchmarks to guide implementation improvements and release decisions." },
    { heading: "The result", body: "Delivered a production conversational channel for shopping and account tasks, with more predictable actions and practical self-service capabilities. Enabled product and engineering teams to access operational insights through a dedicated analytics experience." },
  ] },
  { icon: "web", category: "CUSTOMER EXPERIENCE", year: "2025", shortTitle: "Customer-facing experiences", title: "Less friction. More thoughtful web experiences.", summary: "Led a configurable-product flow redesign and improved the systems behind product pages, from content flexibility to trustworthy engagement analytics.", tags: ["React", "State management", "A/B testing", "Analytics"], role: "Led implementation of the two-step configuration flow", outcome: "A/B-tested experience rolled out to production", details: [
    { heading: "The problem", body: "A lengthy product configuration flow created navigation friction. Product and business teams also needed reliable engagement data and more flexibility to experiment with content." },
    { heading: "My contribution", body: "Led the implementation of a two-step configuration experience, preserving selections as users moved between steps. Extended reusable content components and improved product-template tracking and component-impression accuracy." },
    { heading: "Engineering decisions", body: "Kept user state intact across navigation, consolidated redundant tracking, and corrected repeat impression events caused by component re-renders. Partnered with cross-functional teams to validate behavior and support experimentation." },
    { heading: "The result", body: "The redesigned configuration experience progressed from an A/B test to a full production rollout. Analytics improvements gave stakeholders cleaner engagement data, while content enhancements supported more independent experimentation." },
  ] },
  { icon: "tools", category: "DEVELOPER EXPERIENCE", year: "2025", shortTitle: "Tools that help teams", title: "Making the invisible parts of a system visible.", summary: "Built a browser extension that exposes component ownership, active experiments, and deployment context directly on product pages, helping teams investigate and validate changes.", tags: ["Chrome extension", "APIs", "Persistent state", "Documentation"], role: "Designed and developed the browser extension", outcome: "Shared ownership, experiment, and deployment visibility", details: [
    { heading: "The problem", body: "Understanding which team owned a page component, which experiment was running, and which deployment was being viewed required manual investigation and coordination." },
    { heading: "My contribution", body: "Designed and developed a Chrome extension with component highlighting, live ownership mappings, experiment visibility, and environment context. Added persistent view preferences and fallback data so the tool remains useful when its service is unavailable." },
    { heading: "Beyond the interface", body: "Supported application security through vulnerability remediation across multiple repositories. Created repository setup and architecture documentation to make onboarding and independent troubleshooting easier for the AI team." },
    { heading: "The result", body: "Gave engineering, QA, and product teams a shared view of complex page structures and experiments. Combined useful tooling with clearer documentation and maintenance practices." },
  ] },
];
export const principles = [
  { title: "Simplify the experience", description: "Understand the workflow first. Let the software carry the complexity so people can focus on their task.", example: "Multi-step business operations, one guided experience." },
  { title: "Design for reality", description: "Permissions, partial failures, and recovery belong in the design from the start.", example: "Approval controls and recoverable execution." },
  { title: "Keep people in control", description: "AI should make useful recommendations, explain uncertainty, and confirm consequential actions.", example: "Human review, clear intent, predictable actions." },
  { title: "Validate with evidence", description: "Measure behavior, test the important paths, and use real feedback to guide the next decision.", example: "Performance evaluation and production experimentation." },
];
export const toolGroups = [
  { title: "Frontend", description: "Interfaces that make complex systems approachable.", tools: [{ name: "React", symbol: "✳", color: "cyan" }, { name: "TypeScript", symbol: "TS", color: "blue" }, { name: "JavaScript", symbol: "JS", color: "gold" }, { name: "HTML / CSS", symbol: "</>", color: "orange" }] },
  { title: "Backend & Data", description: "Services, integrations, and dependable persistence.", tools: [{ name: "Python", symbol: "Py", color: "gold" }, { name: "FastAPI", symbol: "ϟ", color: "teal" }, { name: "PostgreSQL", symbol: "Pg", color: "blue" }, { name: "SQLAlchemy", symbol: "SA", color: "coral" }, { name: "Node.js", symbol: "N", color: "green" }, { name: "Java", symbol: "J", color: "orange" }] },
  { title: "Applied AI", description: "Useful intelligence, grounded in real workflows.", tools: [{ name: "LangGraph", symbol: "LG", color: "teal" }, { name: "LLM agents", symbol: "AI", color: "amber" }, { name: "TF-IDF", symbol: "Tf", color: "cyan" }, { name: "DistilBERT", symbol: "DB", color: "violet" }] },
  { title: "Quality & Delivery", description: "Confidence from development through production.", tools: [{ name: "Docker", symbol: "D", color: "blue" }, { name: "Git", symbol: "G", color: "orange" }, { name: "Jenkins", symbol: "J", color: "coral" }, { name: "Jest", symbol: "Jt", color: "coral" }, { name: "Cypress", symbol: "Cy", color: "teal" }, { name: "Snyk", symbol: "S", color: "violet" }] },
];

export const education = [
  { degree: "Master of Business Administration (MBA)", concentration: "Concentration in Data Analytics", school: "Louisiana State University Shreveport", dates: "July 2026 — Present" },
  { degree: "B.S. Computer Science", concentration: "", school: "Macaulay Honors College, CUNY", dates: "May 2024 · GPA 3.90" },
];
